// Iterate through the ARRAY of bookmarked hikes (document ID's)
bookmarks.forEach(thisHikeID => {
    console.log(thisHikeID);
    db.collection("reviews").doc(thisHikeID).get().then(doc => {
      var title = doc.data().name; // get value of the "name" key
      var hikeCode = doc.data().code; //get unique ID to each hike to be used for fetching right image
      var hikeLength = doc.data().length; //gets the length field
      var docID = doc.id;  //this is the autogenerated ID of the document
  
      db.collection("reviews").doc(thisHikeID).collection("reviews").get().then(allReviews => {
        reviews = allReviews.docs;
        console.log(reviews);
        reviews.forEach(review => {
          var description = review.data().description; //gets the length field
          var image = review.data().image;
          var time = review.data().timestamp.toDate();
          console.log(time)
  
          let reviewCard = reviewCardTemplate.content.cloneNode(true);
          reviewCard.querySelector('.time').innerHTML = new Date(time).toLocaleString();
          reviewCard.querySelector('.image').src = image;
          reviewCard.querySelector('.description').innerHTML = `Description: ${description}`;
          reviewCardGroup.appendChild(reviewCard);
        })
      })
    })
  });
  